import { FormEvent, useEffect, useMemo, useState } from 'react';
import { Link, Navigate, useParams } from 'react-router-dom';
import { accessToken, errorMessage } from '../../../api/client';
import { emergencyIssueApi, EmergencyIssue } from '../../../api/emergencyIssueApi';
import { projectApi, ProjectResponse } from '../../../api/projectApi';
import { AppNavigation } from '../../../app/AppNavigation';
import { AuthenticatedImage } from '../../../app/AuthenticatedImage';
import { useLanguage } from '../../../app/LanguageContext';

export function EmergencyIssuesPage(){
  const groupId=Number(useParams().groupId); const {t,language}=useLanguage();
  const [issues,setIssues]=useState<EmergencyIssue[]>([]); const [projects,setProjects]=useState<ProjectResponse[]>([]);
  const [projectId,setProjectId]=useState(''); const [title,setTitle]=useState(''); const [description,setDescription]=useState('');
  const [audience,setAudience]=useState<EmergencyIssue['audience']>('PROJECT_PARTICIPANTS'); const [image,setImage]=useState<File>();
  const [loading,setLoading]=useState(true); const [pending,setPending]=useState(false); const [error,setError]=useState('');
  const preview=useMemo(()=>image?URL.createObjectURL(image):'',[image]);
  useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
  async function refresh(){const [issueValues,projectValues]=await Promise.all([emergencyIssueApi.list(groupId),projectApi.list(groupId)]);setIssues(issueValues);setProjects(projectValues.filter(p=>p.status!=='ARCHIVED'));if(!projectId&&projectValues.length)setProjectId(String(projectValues[0].id));}
  useEffect(()=>{if(!Number.isInteger(groupId)||groupId<1){setLoading(false);return;}refresh().catch(e=>setError(errorMessage(e))).finally(()=>setLoading(false));},[groupId]);
  async function create(event:FormEvent){event.preventDefault();if(!projectId)return;setPending(true);setError('');try{let created=await emergencyIssueApi.create(groupId,{projectId:Number(projectId),title:title.trim(),description:description.trim()||undefined,audience});if(image)created=await emergencyIssueApi.uploadImage(created.id,image);setIssues(v=>[created,...v]);setTitle('');setDescription('');setImage(undefined);window.dispatchEvent(new Event('notifications:refresh'));}catch(e){setError(errorMessage(e));}finally{setPending(false);}}
  async function toggle(issue:EmergencyIssue){setPending(true);setError('');try{const updated=await emergencyIssueApi.status(issue.id,issue.status==='OPEN'?'RESOLVED':'OPEN',issue.version);setIssues(v=>v.map(x=>x.id===updated.id?updated:x).sort((a,b)=>a.status.localeCompare(b.status)||b.createdAt.localeCompare(a.createdAt)));}catch(e){setError(errorMessage(e));}finally{setPending(false);}}
  if(!accessToken.get())return <Navigate to={`/login?next=${encodeURIComponent(`/groups/${groupId}/emergency-issues`)}`} replace/>;
  if(loading)return <main className="center-page">{t('긴급 이슈를 불러오는 중...','Loading urgent issues...')}</main>;
  return <><AppNavigation/><main className="app-page emergency-page"><header className="emergency-page-header"><div><span className="page-eyebrow">URGENT CONTROL</span><h1>{t('긴급 이슈 관리','Urgent issue management')}</h1><p>{t('프로젝트 중 즉시 공유해야 할 문제를 사진과 함께 알리고 해결 여부를 추적합니다.','Alert the right people immediately and track resolution with visual context.')}</p></div><Link className="secondary button-link" to={`/groups/${groupId}/dashboard`}>← {t('대시보드','Dashboard')}</Link></header>
  <section className="emergency-create-card"><h2>{t('긴급 이슈 알리기','Raise an urgent issue')}</h2><form className="form" onSubmit={create}><div className="form-row"><label className="field"><span>{t('프로젝트','Project')}</span><select required value={projectId} onChange={e=>setProjectId(e.target.value)}><option value="">{t('프로젝트 선택','Select project')}</option>{projects.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="field"><span>{t('알림 대상','Audience')}</span><select value={audience} onChange={e=>setAudience(e.target.value as EmergencyIssue['audience'])}><option value="PROJECT_PARTICIPANTS">{t('프로젝트 참여 인원','Project participants')}</option><option value="WHOLE_TEAM">{t('팀 전체','Whole team')}</option></select></label></div><label className="field"><span>{t('긴급 이슈 제목','Issue title')}</span><input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder={t('무슨 문제가 발생했나요?','What happened?')}/></label><label className="field"><span>{t('상세 내용','Details')}</span><textarea maxLength={5000} value={description} onChange={e=>setDescription(e.target.value)}/></label><label className="emergency-image-picker"><input type="file" accept="image/jpeg,image/png,image/gif" onChange={e=>setImage(e.target.files?.[0])}/>{preview?<img src={preview} alt={t('첨부 이미지 미리보기','Image preview')}/>:<span><b>＋ {t('현장 이미지 추가','Add an image')}</b><small>JPG, PNG, GIF · 5MB</small></span>}</label>{error&&<p className="error">{error}</p>}<button className="danger" disabled={pending||!title.trim()||!projectId}>{pending?t('알리는 중...','Sending...'):t('긴급 이슈 등록 및 알림','Publish and alert')}</button></form></section>
  <section className="emergency-list"><div className="dashboard-panel-title"><div><h2>{t('이슈 현황','Issue status')}</h2><p>{t(`미해결 ${issues.filter(i=>i.status==='OPEN').length}건`,`Open ${issues.filter(i=>i.status==='OPEN').length}`)}</p></div></div>{issues.length===0?<p className="empty-state">{t('등록된 긴급 이슈가 없습니다.','No urgent issues.')}</p>:issues.map(issue=><article className={`emergency-card ${issue.status.toLowerCase()}`} key={issue.id}>{issue.imageUrl&&<AuthenticatedImage src={issue.imageUrl} alt=""/>}<div><header><span>{issue.status==='OPEN'?t('대응 필요','Action required'):t('해결됨','Resolved')}</span><small>{issue.audience==='WHOLE_TEAM'?t('팀 전체 알림','Whole team'):t('프로젝트 참여자 알림','Project participants')}</small></header><h3>{issue.title}</h3><Link to={`/projects/${issue.projectId}/flow`}>{issue.projectName}</Link>{issue.description&&<p>{issue.description}</p>}<footer><small>{issue.createdByNickname} · {new Intl.DateTimeFormat(language==='ko'?'ko-KR':'en-US',{dateStyle:'medium',timeStyle:'short'}).format(new Date(issue.createdAt))}</small>{issue.canManage&&<button className={issue.status==='OPEN'?'primary':'secondary'} type="button" disabled={pending} onClick={()=>toggle(issue)}>{issue.status==='OPEN'?t('해결 처리','Mark resolved'):t('다시 열기','Reopen')}</button>}</footer></div></article>)}</section></main></>;
}
