CREATE TABLE project_issue_nodes (
    id BIGINT NOT NULL AUTO_INCREMENT,
    project_id BIGINT NOT NULL,
    parent_id BIGINT NULL,
    assignee_member_id BIGINT NULL,
    created_by_member_id BIGINT NOT NULL,
    level ENUM('MAJOR', 'MIDDLE', 'ISSUE') NOT NULL,
    title VARCHAR(160) NOT NULL,
    description TEXT NULL,
    status ENUM('OPEN', 'IN_PROGRESS', 'BLOCKED', 'DONE') NOT NULL DEFAULT 'OPEN',
    sort_order INT NOT NULL DEFAULT 0,
    due_date DATE NULL,
    archived_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    INDEX idx_project_issue_nodes_project_parent (project_id, parent_id, archived_at, sort_order, id),
    INDEX idx_project_issue_nodes_assignee (assignee_member_id, status, archived_at),
    CONSTRAINT fk_project_issue_nodes_project FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_project_issue_nodes_parent FOREIGN KEY (parent_id) REFERENCES project_issue_nodes (id),
    CONSTRAINT fk_project_issue_nodes_assignee FOREIGN KEY (assignee_member_id) REFERENCES group_members (id),
    CONSTRAINT fk_project_issue_nodes_created_by FOREIGN KEY (created_by_member_id) REFERENCES group_members (id)
) ENGINE = InnoDB;

CREATE TABLE project_issue_checklist_items (
    id BIGINT NOT NULL AUTO_INCREMENT,
    issue_id BIGINT NOT NULL,
    content VARCHAR(500) NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    completed_by_member_id BIGINT NULL,
    completed_at DATETIME(6) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    INDEX idx_project_issue_checklist_order (issue_id, sort_order, id),
    CONSTRAINT fk_project_issue_checklist_issue FOREIGN KEY (issue_id) REFERENCES project_issue_nodes (id),
    CONSTRAINT fk_project_issue_checklist_completed_by FOREIGN KEY (completed_by_member_id) REFERENCES group_members (id)
) ENGINE = InnoDB;

CREATE TABLE project_issue_images (
    id BIGINT NOT NULL AUTO_INCREMENT,
    issue_id BIGINT NOT NULL,
    uploaded_by_member_id BIGINT NOT NULL,
    storage_key VARCHAR(500) NOT NULL,
    original_filename VARCHAR(255) NOT NULL,
    content_type VARCHAR(100) NOT NULL,
    size_bytes BIGINT NOT NULL,
    checksum_sha256 CHAR(64) NOT NULL,
    sort_order INT NOT NULL DEFAULT 0,
    created_at DATETIME(6) NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_project_issue_images_storage_key (storage_key),
    UNIQUE KEY uk_project_issue_images_checksum (issue_id, checksum_sha256),
    INDEX idx_project_issue_images_order (issue_id, sort_order, id),
    CONSTRAINT fk_project_issue_images_issue FOREIGN KEY (issue_id) REFERENCES project_issue_nodes (id),
    CONSTRAINT fk_project_issue_images_uploaded_by FOREIGN KEY (uploaded_by_member_id) REFERENCES group_members (id)
) ENGINE = InnoDB;
