CREATE TABLE project_documents (
    id BIGINT NOT NULL AUTO_INCREMENT,
    project_id BIGINT NOT NULL,
    issue_node_id BIGINT NULL,
    created_by_member_id BIGINT NOT NULL,
    document_type ENUM('LINK', 'FILE') NOT NULL,
    title VARCHAR(160) NOT NULL,
    external_url VARCHAR(1000) NULL,
    storage_key VARCHAR(500) NULL,
    original_filename VARCHAR(255) NULL,
    content_type VARCHAR(120) NULL,
    size_bytes BIGINT NULL,
    checksum_sha256 CHAR(64) NULL,
    created_at DATETIME(6) NOT NULL,
    deleted_at DATETIME(6) NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_project_documents_storage_key (storage_key),
    INDEX idx_project_documents_location (project_id, issue_node_id, deleted_at, created_at, id),
    INDEX idx_project_documents_checksum (project_id, issue_node_id, checksum_sha256, deleted_at),
    CONSTRAINT fk_project_documents_project FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_project_documents_issue FOREIGN KEY (issue_node_id) REFERENCES project_issue_nodes (id),
    CONSTRAINT fk_project_documents_created_by FOREIGN KEY (created_by_member_id) REFERENCES group_members (id)
) ENGINE = InnoDB;
