CREATE TABLE task_assignee_change_requests (
    id BIGINT NOT NULL AUTO_INCREMENT,
    task_id BIGINT NOT NULL,
    requested_by_member_id BIGINT NOT NULL,
    proposed_assignee_member_id BIGINT NOT NULL,
    reviewed_by_member_id BIGINT NULL,
    status VARCHAR(20) NOT NULL,
    reason VARCHAR(500) NULL,
    review_note VARCHAR(500) NULL,
    created_at DATETIME(6) NOT NULL,
    reviewed_at DATETIME(6) NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    INDEX idx_assignee_change_task_status (task_id, status, created_at),
    INDEX idx_assignee_change_group_status (status, created_at),
    CONSTRAINT fk_assignee_change_task FOREIGN KEY (task_id) REFERENCES tasks (id),
    CONSTRAINT fk_assignee_change_requested_by FOREIGN KEY (requested_by_member_id) REFERENCES group_members (id),
    CONSTRAINT fk_assignee_change_proposed FOREIGN KEY (proposed_assignee_member_id) REFERENCES group_members (id),
    CONSTRAINT fk_assignee_change_reviewed_by FOREIGN KEY (reviewed_by_member_id) REFERENCES group_members (id)
);

CREATE TABLE emergency_issues (
    id BIGINT NOT NULL AUTO_INCREMENT,
    group_id BIGINT NOT NULL,
    project_id BIGINT NOT NULL,
    created_by_member_id BIGINT NOT NULL,
    title VARCHAR(160) NOT NULL,
    description TEXT NULL,
    audience VARCHAR(30) NOT NULL,
    status VARCHAR(20) NOT NULL,
    image_url VARCHAR(500) NULL,
    resolved_at DATETIME(6) NULL,
    created_at DATETIME(6) NOT NULL,
    updated_at DATETIME(6) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    PRIMARY KEY (id),
    INDEX idx_emergency_group_status_created (group_id, status, created_at),
    INDEX idx_emergency_project_status_created (project_id, status, created_at),
    CONSTRAINT fk_emergency_group FOREIGN KEY (group_id) REFERENCES work_groups (id),
    CONSTRAINT fk_emergency_project FOREIGN KEY (project_id) REFERENCES projects (id),
    CONSTRAINT fk_emergency_created_by FOREIGN KEY (created_by_member_id) REFERENCES group_members (id)
);
